name: Test Automation Framework

on:
  schedule:
  - cron: 00 18 *  *  *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Running test automation framework
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadLess=true

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Test Logs
        path: logs/

    - name: Upload Screenshots as artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: screenshots
        path: screenshots/
        
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: Reports
        path: report.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"

    - name: Copy reports to gh-pages Folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l

    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        folder: public/extent-reports/
        token: ${{ secrets.PAT2724 }}
        clean: true
      

